export const REQUIRED_VARS = [
      "COGS_AND_STEAM_QUERY_PORT",
  "COGS_AND_STEAM_SERVER_IP",
  "COGS_AND_STEAM_SERVER_PORT",
  "DISCORD_MAIN_BOT_TOKEN",
  "DISCORD_TICKET_MESSAGE_CHANNEL_ID",
  "NODE_ENV",
  "PORT",
  "SERVER_DOMAIN",
  "SERVER_LOADER",
  "SERVER_NAME",
  "WEB_ADMIN_PANEL_URL",
  "WEB_MAP_URL",
  "WEB_MODPACK_URL",
  "WEB_URL",
    ] as const;

    export type RequiredVar = typeof REQUIRED_VARS[number];
    export default REQUIRED_VARS;
    